// GENERATED SCORING DATA - Auto-aligned with quiz-copy.ts
export const ALIGN_QUESTIONS = {
  1: {
    text: "Enjoying life when I can matters more to me than preserving spending later.",
    category: "Spender",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Front Loaded" },
      "Agree": { points: 1, trait: "Front Loaded" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Back Loaded" },
      "Strongly Disagree": { points: 2, trait: "Back Loaded" },
    },
  },
  2: {
    text: "A steady, reliable income matters more to me than maximizing my net worth.",
    category: "Mindset",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Income Mindset" },
      "Agree": { points: 1, trait: "Income Mindset" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Net Worth Mindset" },
      "Strongly Disagree": { points: 2, trait: "Net Worth Mindset" },
    },
  },
  3: {
    text: "I'd rather spend more in the early years of retirement while I'm more active.",
    category: "Spender",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Front Loaded" },
      "Agree": { points: 1, trait: "Front Loaded" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Back Loaded" },
      "Strongly Disagree": { points: 2, trait: "Back Loaded" },
    },
  },
  4: {
    text: "I want my essential living expenses covered regardless of market performance.",
    category: "Income Source",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Contractual" },
      "Agree": { points: 1, trait: "Contractual" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Market Driven" },
      "Strongly Disagree": { points: 2, trait: "Market Driven" },
    },
  },
  5: {
    text: "I am okay if my retirement income changes based on market performance.",
    category: "Income Source",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Contractual" },
      "Agree": { points: 1, trait: "Contractual" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Market Driven" },
      "Strongly Disagree": { points: 2, trait: "Market Driven" },
    },
  },
  6: {
    text: "Stable income for my essential needs matters more to me than chasing investment upside.",
    category: "Income Source",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Contractual" },
      "Agree": { points: 1, trait: "Contractual" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Market Driven" },
      "Strongly Disagree": { points: 2, trait: "Market Driven" },
    },
  },
  7: {
    text: "I'm comfortable with income variability if it increases long-term growth of my net worth.",
    category: "Income Source",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Contractual" },
      "Agree": { points: 1, trait: "Contractual" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Market Driven" },
      "Strongly Disagree": { points: 2, trait: "Market Driven" },
    },
  },
  8: {
    text: "I prefer having the ability to change my mind over locking in guaranteed long-term outcomes.",
    category: "Income Structure",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Committed" },
      "Agree": { points: 1, trait: "Committed" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Adjustable" },
      "Strongly Disagree": { points: 2, trait: "Adjustable" },
    },
  },
  9: {
    text: "I want the flexibility to adjust my retirement income strategy as life changes.",
    category: "Income Structure",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Committed" },
      "Agree": { points: 1, trait: "Committed" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Adjustable" },
      "Strongly Disagree": { points: 2, trait: "Adjustable" },
    },
  },
  10: {
    text: "The longer my planning timeframe, the more important a stable, consistent retirement income strategy becomes to me.",
    category: "Income Structure",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Committed" },
      "Agree": { points: 1, trait: "Committed" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Adjustable" },
      "Strongly Disagree": { points: 2, trait: "Adjustable" },
    },
  },
  11: {
    text: "I would rather adapt over time than commit to one long-term strategy.",
    category: "Income Structure",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Committed" },
      "Agree": { points: 1, trait: "Committed" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Adjustable" },
      "Strongly Disagree": { points: 2, trait: "Adjustable" },
    },
  },
  12: {
    text: "I'm comfortable drawing from my principal if it improves the quality of my retirement.",
    category: "Mindset",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Income Mindset" },
      "Agree": { points: 1, trait: "Income Mindset" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Net Worth Mindset" },
      "Strongly Disagree": { points: 2, trait: "Net Worth Mindset" },
    },
  },
  13: {
    text: "I will sacrifice lifestyle in retirement to preserve my portfolio's value.",
    category: "Mindset",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Income Mindset" },
      "Agree": { points: 1, trait: "Income Mindset" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Net Worth Mindset" },
      "Strongly Disagree": { points: 2, trait: "Net Worth Mindset" },
    },
  },
  14: {
    text: "I will sell some investments for 'pop-up' expenses.",
    category: "Liquidity",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Cash Liquidity" },
      "Agree": { points: 1, trait: "Cash Liquidity" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Investment Liquidity" },
      "Strongly Disagree": { points: 2, trait: "Investment Liquidity" },
    },
  },
  15: {
    text: "Having a surplus of cash available helps me feel calm.",
    category: "Liquidity",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Cash Liquidity" },
      "Agree": { points: 1, trait: "Cash Liquidity" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Investment Liquidity" },
      "Strongly Disagree": { points: 2, trait: "Investment Liquidity" },
    },
  },
  16: {
    text: "What is your biggest concern today?",
    category: "Intent",
    engine: "Tier Calc",
    answers: {
      "Healthcare concern": { points: 1, trait: "Specific concern" },
      "How do I turn assets into income?": { points: 1, trait: "Specific concern" },
      "Inflation concerns": { points: 1, trait: "Specific concern" },
      "Tax efficiency": { points: 1, trait: "Specific concern" },
      "I can’t afford a market crash right now.": { points: 1, trait: "Specific concern" },
    },
  },
  17: {
    text: "Are you looking for an advisor to customize or build a retirement strategy?",
    category: "Intent",
    engine: "Tier Calc",
    answers: {
      "Build New": { points: 1, trait: "Advisory" },
      "Update Existing": { points: 1, trait: "Advisory" },
      "Neither": { points: 0, trait: "No advisory" },
    },
  },
  18: {
    text: "How long until you plan to retire?",
    category: "Timeline",
    engine: "Tier Calc",
    answers: {
      "0 – 3 years": { points: 10, trait: "Urgent" },
      "Already Retired": { points: 7, trait: "Distribution" },
      "3 – 5 years": { points: 8, trait: "Near-term" },
      "5 – 10 years": { points: 4, trait: "Mid" },
      "10 – 15 years": { points: 1, trait: "Long" },
      "15+ years": { points: 0, trait: "Very long" },
    },
  },
  19: {
    text: "Structuring cash flows by time periods helps me feel in control.",
    category: "Payout Pattern",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Phased Income" },
      "Agree": { points: 1, trait: "Phased Income" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Lifetime Income" },
      "Strongly Disagree": { points: 2, trait: "Lifetime Income" },
    },
  },
  20: {
    text: "I prefer having income streams that last the rest of my life.",
    category: "Payout Pattern",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Phased Income" },
      "Agree": { points: 1, trait: "Phased Income" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Lifetime Income" },
      "Strongly Disagree": { points: 2, trait: "Lifetime Income" },
    },
  },
  21: {
    text: "Organizing income into time segments (every 5–7 years) makes sense to me.",
    category: "Payout Pattern",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Phased Income" },
      "Agree": { points: 1, trait: "Phased Income" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Lifetime Income" },
      "Strongly Disagree": { points: 2, trait: "Lifetime Income" },
    },
  },
  22: {
    text: "If I see cash in the bank, I worry that it should be invested.",
    category: "Liquidity",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Cash Liquidity" },
      "Agree": { points: 1, trait: "Cash Liquidity" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Investment Liquidity" },
      "Strongly Disagree": { points: 2, trait: "Investment Liquidity" },
    },
  },
  23: {
    text: "I believe a financial professional can identify risks in my retirement plan that I may overlook on my own.",
    category: "Advisor Value",
    engine: "Quadrant (-3 to +3)",
    answers: {
      "Strongly Agree": { points: 3, trait: "High advisor value" },
      "Agree": { points: 2, trait: "High advisor value" },
      "Neutral": { points: 1, trait: "High advisor value" },
      "Disagree": { points: 0, trait: "Neutral" },
      "Strongly Disagree": { points: -3, trait: "Low advisor value" },
    },
  },
  24: {
    text: "I prefer to be presented with a few vetted options, rather than researching every available financial product myself.",
    category: "Advisor Value",
    engine: "Quadrant (-3 to +3)",
    answers: {
      "Strongly Agree": { points: 3, trait: "High advisor value" },
      "Agree": { points: 2, trait: "High advisor value" },
      "Neutral": { points: 1, trait: "High advisor value" },
      "Disagree": { points: 0, trait: "Neutral" },
      "Strongly Disagree": { points: -3, trait: "Low advisor value" },
    },
  },
  25: {
    text: "The primary value of a financial advisor is providing access to exclusive investment opportunities I cannot reach on my own.",
    category: "Advisor Value",
    engine: "Quadrant (-3 to +3)",
    answers: {
      "Strongly Agree": { points: 3, trait: "High advisor value" },
      "Agree": { points: 2, trait: "High advisor value" },
      "Neutral": { points: 1, trait: "High advisor value" },
      "Disagree": { points: 0, trait: "Neutral" },
      "Strongly Disagree": { points: -3, trait: "Low advisor value" },
    },
  },
  26: {
    text: "I understand financial concepts like: sequence of returns risk and tax loss harvesting.",
    category: "Self Efficacy",
    engine: "Quadrant (-3 to +3)",
    answers: {
      "Strongly Agree": { points: 3, trait: "High self efficacy" },
      "Agree": { points: 2, trait: "High self efficacy" },
      "Neutral": { points: 1, trait: "High self efficacy" },
      "Disagree": { points: 0, trait: "Neutral" },
      "Strongly Disagree": { points: -3, trait: "Low self efficacy" },
    },
  },
  27: {
    text: "I feel overwhelmed by the complexity of retirement income planning.",
    category: "Self Efficacy",
    engine: "Quadrant (-3 to +3)",
    answers: {
      "Strongly Agree": { points: 3, trait: "High self efficacy" },
      "Agree": { points: 2, trait: "High self efficacy" },
      "Neutral": { points: 1, trait: "High self efficacy" },
      "Disagree": { points: 0, trait: "Neutral" },
      "Strongly Disagree": { points: -3, trait: "Low self efficacy" },
    },
  },
  28: {
    text: "If I had to implement my retirement plan tomorrow, without any outside help, I am confident I would succeed.",
    category: "Self Efficacy",
    engine: "Quadrant (-3 to +3)",
    answers: {
      "Strongly Agree": { points: 3, trait: "High self efficacy" },
      "Agree": { points: 2, trait: "High self efficacy" },
      "Neutral": { points: 1, trait: "High self efficacy" },
      "Disagree": { points: 0, trait: "Neutral" },
      "Strongly Disagree": { points: -3, trait: "Low self efficacy" },
    },
  },
  29: {
    text: "What is your age range?",
    category: "Demographics",
    engine: "Tier Calc",
    answers: {
      "Under 50": { points: 1, trait: "Age band" },
      "51–62": { points: 1, trait: "Age band" },
      "62–67": { points: 1, trait: "Age band" },
      "68–74": { points: 1, trait: "Age band" },
      "75+": { points: 1, trait: "Age band" },
    },
  },
  30: {
    text: "About how much do you currently have saved and invested (excluding your home)?",
    category: "Demographics",
    engine: "Tier Calc",
    answers: {
      "$3M+": { points: 8, trait: "Asset level" },
      "$1.5M – $3M": { points: 8, trait: "Asset level" },
      "$750k – $1.5M": { points: 4, trait: "Asset level" },
      "$250k – $750k": { points: 4, trait: "Asset level" },
      "Less than $250k": { points: 1, trait: "Asset level" },
    },
  },
  31: {
    text: "Which of the following apply to you?",
    category: "Demographics",
    engine: "Tier Calc",
    answers: {
      "$5M+ active investments": { points: 1, trait: "Financial" },
      "Net worth excl. home ≥ $2.2M": { points: 1, trait: "Financial" },
      "$1.1M+ managed by advisor": { points: 1, trait: "Financial" },
      "Individual income $200k+ (past 2 yrs)": { points: 1, trait: "Financial" },
      "Household income $300k+ (past 2 yrs)": { points: 1, trait: "Financial" },
      "Net worth excl. home ≥ $1M": { points: 1, trait: "Financial" },
      "None of the above": { points: 1, trait: "Financial" },
    },
  },
  32: {
    text: "A financial need, late in life, keeps me up at night.",
    category: "Spender",
    engine: "Bipolar (0-2)",
    answers: {
      "Strongly Agree": { points: 2, trait: "Front Loaded" },
      "Agree": { points: 1, trait: "Front Loaded" },
      "Neutral": { points: 0, trait: "—" },
      "Disagree": { points: 1, trait: "Back Loaded" },
      "Strongly Disagree": { points: 2, trait: "Back Loaded" },
    },
  },
  33: {
    text: "Which types of accounts hold your retirement savings?",
    category: "Demographics",
    engine: "Tier Calc",
    answers: {
      "pre_tax": { points: 1, trait: "Tax" },
      "roth": { points: 1, trait: "Tax" },
      "taxable": { points: 1, trait: "Tax" },
      "not_sure": { points: 0, trait: "Tax" },
    },
  },
  34: {
    text: "State of Residence",
    category: "Demographics",
    engine: "Profile",
    answers: {
    },
  },
};

export const BIPOLAR_TRAIT_CATEGORIES = {
  incomeSource: { a: "Contractual", b: "Market Driven" },
  incomeStructure: { a: "Committed", b: "Adjustable" },
  mindset: { a: "Income Mindset", b: "Net Worth Mindset" },
  liquidity: { a: "Cash Liquidity", b: "Investment Liquidity" },
  spender: { a: "Front Loaded", b: "Back Loaded" },
  payoutPattern: { a: "Phased Income", b: "Lifetime Income" },
};

export const QUADRANT_PERSONAS = {
  "HighAdvisor_HighEfficacy": "Collaborative Partner",
  "HighAdvisor_LowEfficacy": "Strategic Delegator",
  "LowAdvisor_HighEfficacy": "Confident Investor",
  "LowAdvisor_LowEfficacy": "Independent Learner",
};
